server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.liangcang.pojo
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.31.155.30/gw?serverTimezone=UTC
    username: root
    password: asdfRV123
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  level:
    com.qf.liangcang.mapper: debug